### ISSUE TITLE
MSE couldn't  get all track informations through htmlmediaelement.audiotracks. 

### ISSUE THREAD

**Issue by Pengfei-Yin** [HbbTV-Association/ReferenceApplication#45]
When we are testing 1.7 Multiple audio (v4) in MSE-EME mode, case failed because js doesn't get correct track information. After debugging js code, we found that Reference Application use dash.js to play dash strearm in MSE testcases.
For MSE, browser could not get all track information of dash stream, unless all tracks have created a sourcebuffer. So we think maybe Reference Application could use function gettracksfor("audio") in dash.js to get all track information instead of using video.audiotracks.

**Comment by Murmur** [comment]
Fixed in a staging release, MSEEME(dashjs) is using dashjsAPI `player.getTracksFor("text|audio")` to list available subtitles or audios.
https://refapp.hbbtv.org/staging/catalogue/

Github master source codes soon pushed up-to-date, for the moment still has an older sources due to a restructuring of the source code pipeline.

**Comment by juhajoki** [comment]
This is fixed for audio tracks

**Comment by juhajoki** [comment]
track selection is fixed, but displaying of subtitles in MSE mode is still broken.

**Comment by Murmur** [comment]
Production and Staging has an updated dashjs library and switching subtitles should work in MSE player mode as well. See `1.3.1 out-of-band subtitles (xml link in manifest)` and `1.4 in-band subtitles (m4s segments)`. 

https://refapp.hbbtv.org/production/catalogue/
https://refapp.hbbtv.org/staging/catalogue/
